import type { Collection, CollectionData, NFT } from "./types";
import { BASE_PATH } from "./basePath";

/**
 * Runtime NFT data access.
 *
 * Data lives in static JSON files under /public/data/{collection}.json,
 * fetched lazily (once) and cached in memory. No API, no key, no cost.
 * Files are generated by scripts/fetch-metadata.ts.
 */

const cache = new Map<Collection, CollectionData>();
const inflight = new Map<Collection, Promise<CollectionData>>();

async function loadCollection(collection: Collection): Promise<CollectionData> {
  const cached = cache.get(collection);
  if (cached) return cached;

  const existing = inflight.get(collection);
  if (existing) return existing;

  const promise = fetch(`${BASE_PATH}/data/${collection}.json`)
    .then((res) => {
      if (!res.ok) throw new Error(`Failed to load ${collection} data`);
      return res.json() as Promise<CollectionData>;
    })
    .then((data) => {
      cache.set(collection, data);
      inflight.delete(collection);
      return data;
    })
    .catch((err) => {
      inflight.delete(collection);
      throw err;
    });

  inflight.set(collection, promise);
  return promise;
}

/** Warm the cache (call on collection focus / toggle for instant search). */
export function preloadCollection(collection: Collection): void {
  void loadCollection(collection).catch(() => {});
}

/** Look up a single token. Returns null if the id doesn't exist. */
export async function getNFT(
  collection: Collection,
  id: number
): Promise<NFT | null> {
  const data = await loadCollection(collection);
  const record = data[String(id)];
  if (!record) return null;
  return { id, collection, ...record };
}

/** How many tokens the loaded collection actually has (for grids). */
export async function getCollectionSize(
  collection: Collection
): Promise<number> {
  const data = await loadCollection(collection);
  return Object.keys(data).length;
}

/** Resolve several ids at once (used by the recently-viewed grid). */
export async function getNFTs(
  refs: { collection: Collection; id: number }[]
): Promise<NFT[]> {
  const out: NFT[] = [];
  for (const ref of refs) {
    const nft = await getNFT(ref.collection, ref.id);
    if (nft) out.push(nft);
  }
  return out;
}
